// Generated by CoffeeScript 1.9.1
(function() {
  var browserReload, browserSync, colors, config, get_task, gulp, helpers, plugins, site, site_file, utils;

  site_file = 'build.yaml';

  require('coffee-script/register');

  gulp = require('gulp');

  plugins = require('gulp-load-plugins')();

  plugins.runSequence = require('run-sequence');

  utils = require('gulp-util');

  colors = require('gulp-util').colors;

  browserSync = require('browser-sync');

  browserReload = browserSync.reload;

  helpers = require('./tasks/helpers.coffee');

  site = {
    build_config: {}
  };

  config = helpers.yaml_load(__dirname + "/" + site_file);

  config.serve = utils.env.serve ? true : false;

  config.watch = utils.env.watch ? true : false;

  config.unminify = utils.env.unminify ? true : false;

  config.force = utils.env.force ? true : false;

  config.debug = utils.env.debug ? true : false;

  config.view = utils.env.url ? utils.env.url : false;

  config.ui = utils.env.ui ? "ui" : false;

  config.dataURI = utils.env.datauri ? true : false;

  config.shopify = utils.env.shopify ? true : false;

  config.local = utils.env.shopify ? false : true;

  helpers.copy_config(config, site.build_config);

  helpers.load_data(site, config);

  get_task = function(task, notify) {
    if (notify) {
      helpers.bs_notify(notify);
    }
    return require("./tasks/" + task + ".coffee")(gulp, plugins, config, site);
  };

  gulp.task('default', ['build'], function() {});

  gulp.task('build', function(cb) {
    return plugins.runSequence(['assets', 'vendor'], ['css', 'js'], 'html', 'browser-sync', cb);
  });

  gulp.task('html', get_task("jade", "Jade »»» HTML"));

  gulp.task('css', get_task("stylus", "Stylus »»» CSS"));

  gulp.task('js', get_task("coffee", "CoffeeScript »»» JS"));

  gulp.task('assets', get_task("assets", "Assets »»» Production Assets"));

  gulp.task('vendor', get_task("vendor", "Vendor Assets »»» Production Assets"));

  gulp.task('html-watch', ["html"], browserReload);

  gulp.task('css-watch', ["css"], browserReload);

  gulp.task('js-watch', ["js"], browserReload);

  gulp.task('browser-sync', function() {
    if (config.watch) {
      helpers.browser_sync(config);
      gulp.watch("./" + config.source + "/" + config.jade.cwd + "/**", ['html-watch']);
      gulp.watch("./" + config.source + "/" + config.stylus.cwd + "/**", ['css-watch']);
      gulp.watch("./" + config.source + "/" + config.coffee.cwd + "/**", ['js-watch']);
    }
    if (config.serve) {
      return helpers.serve(config);
    }
  });

  gulp.task('serve', function(cb) {
    helpers.serve(config);
    return cb();
  });

}).call(this);
