# PROJECT CENTRIC
url:
dev_host: localhost
dev_port: 8000
dev_server:  # if given, gAnalytics will not track on dev site
source: '.'

local_server:
    build: __build
    options:
        clean_urls: true
        cache_control: false
        gzip: true
        log: "dev"
        exclude: false
        # charge can't handle more than one `.` so you can hard-code those templates here, if needed
        # routes:
        # error_page: "/templates/404.html"
        # auth:
        #     user: "username"
        #     pass: "password"

data:
    cwd: "data"

# COMPILERS
jade:
    glob:
        - "!**/_*"
        - "**/*.md"
        - "**/*.jade"
        - "!**/wrapper.jade"
    cwd: "src"
    framework:
        cwd: '_frameworks/vefa-html'
        includes:
            - django_templates
            # - django_cms
            # - shopify
    destination: "__build/"
    # shopify: ""


stylus:
    glob:
        - "site.styl"
        # - "site_ie9.styl"
        # - "site_ie8.styl"
    autoprefixer:
        - 'last 2 versions'
        - 'Explorer 9'
        - 'Explorer 10'
    cwd: "css"
    framework:
        cwd: '_frameworks/vefa-css'
    destination: "__build/assets/css"
    # shopify: ""


coffee:
    glob:
      - "main.coffee"
    opts:
      bare: true
      join: true
    cwd: "js"
    destination: "__build/assets/js"
    shopify: ""
    output: app.js


assets:
    glob:
        - "**/*.*"
        - "!**/*.zip"
        - "!**/*.ai"
    cwd: "res"
    destination: "__build/assets/media"
    shopify: ""


vendor:
    glob:
        - "*.*"
    cwd: "vendor"
    destination: "__build/assets/vendor"
    shopify: ""
